--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
distribution_type: module
name: DateTime-Format-HTTP
date: 16 Aug 2003
author: SPOON
version: 0.35
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.11
  Test::Pod: 0.95
requires:
  DateTime: 0.1601
  HTTP::Date: 1.44

private:
  directory:
    - t

provides:
  DateTime::Format::HTTP:
    file: lib/DateTime/Format/HTTP.pm
    version: 0.35

dynamic_config: 0
generated_by: docmaker version 0.91
